- params:
    git:
      repoName: pizza-shop
      branches:
        - master
    scan:
      emailReceivers:
        - saharb@jfrog.com
      projects:
        - workingDirs:
            - action
        - workingDirs:
            - .
